apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: reflow-jobs
  namespace: kofli-dev
  labels:
    strimzi.io/cluster: reflowfy-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
